services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: uppdragsradarn
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    command: >
      bash -c "
        echo 'CREATE SCHEMA IF NOT EXISTS uppdragsradarn;' > /docker-entrypoint-initdb.d/init.sql &&
        docker-entrypoint.sh postgres
      "
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_CONFIG:-./nginx.conf}:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - redis

  redis:
    image: valkey/valkey:latest
    container_name: redis
    environment:
      VALKEY_SAVE_POLICY: "60 1000"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["valkey-server", "--appendonly", "yes"]
    extra_hosts:
      - "dev.uppdragsradarn.se:host-gateway"

volumes:
  postgres_data:
  redis_data: