name: CD Pipeline

on:
  push:
    branches: [ main, develop ]
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B clean package -DskipTests
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: konsultradarn-api
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=ref,event=branch
          type=ref,event=pr
          type=sha
    
    - name: Login to DigitalOcean Container Registry
      uses: docker/login-action@v2
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        password: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deploy-dev:
    needs: build
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save konsultradarn-dev
    
    - name: Set environment variables
      run: |
        echo "REGISTRY_ENDPOINT=registry.digitalocean.com/konsultradarn-dev" >> $GITHUB_ENV
        echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV
    
    - name: Deploy to Dev
      run: |
        cd k8s/dev
        kustomize edit set image ${REGISTRY_ENDPOINT}/konsultradarn-api:${IMAGE_TAG}
        kubectl apply -k .
    
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/konsultradarn-api -n app

  deploy-prod:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    
    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save konsultradarn-prod
    
    - name: Set environment variables
      run: |
        echo "REGISTRY_ENDPOINT=registry.digitalocean.com/konsultradarn-prod" >> $GITHUB_ENV
        echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    
    - name: Deploy to Production
      run: |
        cd k8s/prod
        kustomize edit set image ${REGISTRY_ENDPOINT}/konsultradarn-api:${IMAGE_TAG}
        kubectl apply -k .
    
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/konsultradarn-api -n app